SELECT
    POST_ID,
    LOWER(TRIM(POST_CANONICAL_URL)) AS CANONICAL_URL,
    LOWER(TRIM(POST_URL)) AS POST_URL,
    POST_CATEGORY_NAME AS CATEGORY,
    TEASER_AUTHORS_NAMES AS AUTHOR,
    TAXONOMY_TEAMS AS TEAM,
    POST_TAG_NAMES AS TAGS,
    POST_TITLE AS TITLE,

    TRY_TO_DATE(published_date, 'MON DD, YYYY') AS PUBLISH_DATE,

    TRY_TO_TIMESTAMP_NTZ(
        REGEXP_REPLACE(ACF_UPDATE_DATE_TIME, '[^[:print:]]', ''),
        'MON DD, YYYY, HH12:MI:SS AM'
    ) AS UPDATE_TIMESTAMP,

    CAST(
        TRY_TO_TIMESTAMP_NTZ(
            REGEXP_REPLACE(ACF_UPDATE_DATE_TIME, '[^[:print:]]', ''),
            'MON DD, YYYY, HH12:MI:SS AM'
        ) AS DATE
    ) AS UPDATE_DATE,

    TRY_TO_NUMBER(PRODUCT_CATALOG_COUNT) AS PRODUCT_CATALOG_COUNT,
    TRY_TO_NUMBER(PRODUCT_EMBED_COUNT) AS PRODUCT_EMBED_COUNT

FROM RAW.CONTENT_METADATA;
