CREATE OR REPLACE TABLE MARTS.DIM_CONTENT AS

SELECT
    CONTENT_KEY,
    POST_ID,
    CANONICAL_URL,
    POST_URL,
    TITLE,
    CATEGORY,
    AUTHOR,
    TEAM,
    TAGS,
    PUBLISH_DATE,
    UPDATE_DATE,
    REFRESH_STATUS,
    CONTENT_AGE_DAYS,
    CONTENT_AGE_BUCKET,
    PRODUCT_CATALOG_COUNT,
    PRODUCT_EMBED_COUNT,
    MONETIZED_FLAG
FROM INTERMEDIATE.INT_CONTENT_ATTRIBUTES;
