SELECT
    f.CONTENT_KEY,
    d.POST_ID,
    d.TITLE,
    d.CATEGORY,
    d.AUTHOR,
    d.TEAM,
    d.PUBLISH_DATE,
    d.UPDATE_DATE,
    d.REFRESH_STATUS,
    d.CONTENT_AGE_BUCKET,
    d.MONETIZED_FLAG,
    f.MONTH_DATE,
    f.CLICKS,
    f.PREVIOUS_MONTH_CLICKS,
    f.MOM_CLICK_GROWTH_PCT
FROM MARTS.FACT_CONTENT_SEARCH_PERFORMANCE f
LEFT JOIN MARTS.DIM_CONTENT d
    ON f.CONTENT_KEY = d.CONTENT_KEY;
